### ISSUE TITLE
转发消息失败

### ISSUE THREAD

**Issue by dfmjndm** [haha114514/tarot_hoshino#5]
[2021-09-14 16:12:53,979 tarot] INFO: Message 2089429477 triggered send_playerInfo.
[2021-09-14 16:12:54,090 tarot] INFO: 第0轮
[2021-09-14 16:12:54,090 tarot] INFO: 第1轮
[2021-09-14 16:12:54,091 tarot] INFO: 第2轮
[2021-09-14 16:12:54,091 tarot] INFO: 第3轮
[2021-09-14 16:12:54,092 tarot] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when send_playerInfo handling message 2089429477.
[2021-09-14 16:12:54,092 tarot] ERROR: <ActionFailed data=None, echo={'seq': 2}, msg='EMPTY_NODES', retcode=100, status='failed', wording='未找到任何可发送的合并 转发信息'>
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/service.py", line 220, in wrapper
    return await func(bot, event)
  File "/hobot/hoshino/modules/tarot/tarot.py", line 221, in send_playerInfo
    await hoshino.get_bot().send_group_forward_msg(group_id=ev.group_id, messages=chain)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, msg='EMPTY_NODES', retcode=100, status='failed', wording='未找到任何可发送的合并转发 信息'>

**Comment by KAKAnyaaaaaa** [comment]
我也是9天前的时候加了nickname的注释，就用不来了

**Comment by KAKAnyaaaaaa** [comment]
我也是哎
